org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
# Dependencies
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.92
kubejs_version=26.1.2-8.0.4
curios_version=15.0.0+26.1.2
jei_version=29.29.0.77
# Mod Information
mod_id=mxt
mod_name=MiXianTu
mod_license=All Rights Reserved
mod_version=1.0-alpha.1
mod_group_id=com.iafenvoy.mxt
